resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
  - name: leofs_concourse
    type: git
    source:
      uri: https://github.com/mocchira/leofs_concourse.git
      branch: master
  - name: leofs_ansible
    type: git
    source:
      uri: https://github.com/leo-project/leofs_ansible.git
      branch: master
  - name: leofs_src
    type: git
    source:
      uri: https://github.com/leo-project/leofs.git
      branch: master
  - name: leofs_test2
    type: git
    source:
      uri: https://github.com/leo-project/leofs_test2.git
      branch: feature/concourse
  - name: timer_daily
    type: time
    source: {interval: 24h}
  - name: slack-alert
    type: slack-notification
    source:
      url: {{SLACK_URL}}

jobs:
  - name: leofs_deploy
    plan:
    - aggregate:
      - get: leofs_concourse
      - get: leofs_ansible
      - get: leofs_src
        trigger: true
      - get: timer_daily
        trigger: true

    - task: run_ansible
      file: leofs_concourse/tasks/run_ansible.yml
      params:
        ANSIBLE_KEY: {{ANSIBLE_KEY}}
        ANSIBLE_INVENTORY: leofs_concourse/ansible/hosts.local
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}
      on_failure:
        put: slack-alert
        params:
          text: |
            Deploy LeoFS Failed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID

  - name: integration_test
    plan:
    - aggregate:
      - get: leofs_concourse
      - get: leofs_test2
        trigger: true

    - task: run_leofs_test2
      file: leofs_concourse/tasks/run_leofs_test2.yml
      params:
        ANSIBLE_KEY: {{ANSIBLE_KEY}}
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}
        LEOFS_GW_PORT: {{LEOFS_GW_PORT}}
        LEOFS_MANAGER_NODE: {{LEOFS_MANAGER_NODE}}
      on_failure:
        put: slack-alert
        params:
          text: |
            leofs_test2 Failed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID
